// Code generated by protoc-gen-go.
// source: AgentMessage.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AgentMessage_MessageIdentifier int32

const (
	AgentMessage_MESSAGE_SUCCESS              AgentMessage_MessageIdentifier = 0
	AgentMessage_MESSAGE_FILE_NOT_FOUND       AgentMessage_MessageIdentifier = 1
	AgentMessage_MESSAGE_WMI_SERVICE_DISABLED AgentMessage_MessageIdentifier = 2
	AgentMessage_MESSAGE_WMI_ERROR            AgentMessage_MessageIdentifier = 3
	// Client clock changed - No parameters
	AgentMessage_MESSAGE_CLIENTTIMECLOCKCHANGE AgentMessage_MessageIdentifier = 4
	// Broker had to purge messages from queue - Data loss date range in message description
	AgentMessage_MESSAGE_BROKERDATALOSS AgentMessage_MessageIdentifier = 5
	// Client has error opening event log (no monitoring possible) - Event Log is corrupt and must be deleted by Administrator
	AgentMessage_MESSAGE_EVENTLOGDAMAGED AgentMessage_MessageIdentifier = 6
	// AgentStatus timer did not fire on time
	AgentMessage_MESSAGE_AGENTSTATUS_TIMER_DID_NOT_FIRE AgentMessage_MessageIdentifier = 7
	// FileContents message was lost
	AgentMessage_MESSAGE_FILECONTENTS_TRANSMISSION_LOSS AgentMessage_MessageIdentifier = 8
	// MD5 Generation error
	AgentMessage_MESSAGE_MD5_GENERATION_ERROR AgentMessage_MessageIdentifier = 9
)

var AgentMessage_MessageIdentifier_name = map[int32]string{
	0: "MESSAGE_SUCCESS",
	1: "MESSAGE_FILE_NOT_FOUND",
	2: "MESSAGE_WMI_SERVICE_DISABLED",
	3: "MESSAGE_WMI_ERROR",
	4: "MESSAGE_CLIENTTIMECLOCKCHANGE",
	5: "MESSAGE_BROKERDATALOSS",
	6: "MESSAGE_EVENTLOGDAMAGED",
	7: "MESSAGE_AGENTSTATUS_TIMER_DID_NOT_FIRE",
	8: "MESSAGE_FILECONTENTS_TRANSMISSION_LOSS",
	9: "MESSAGE_MD5_GENERATION_ERROR",
}
var AgentMessage_MessageIdentifier_value = map[string]int32{
	"MESSAGE_SUCCESS":                        0,
	"MESSAGE_FILE_NOT_FOUND":                 1,
	"MESSAGE_WMI_SERVICE_DISABLED":           2,
	"MESSAGE_WMI_ERROR":                      3,
	"MESSAGE_CLIENTTIMECLOCKCHANGE":          4,
	"MESSAGE_BROKERDATALOSS":                 5,
	"MESSAGE_EVENTLOGDAMAGED":                6,
	"MESSAGE_AGENTSTATUS_TIMER_DID_NOT_FIRE": 7,
	"MESSAGE_FILECONTENTS_TRANSMISSION_LOSS": 8,
	"MESSAGE_MD5_GENERATION_ERROR":           9,
}

func (x AgentMessage_MessageIdentifier) Enum() *AgentMessage_MessageIdentifier {
	p := new(AgentMessage_MessageIdentifier)
	*p = x
	return p
}
func (x AgentMessage_MessageIdentifier) String() string {
	return proto.EnumName(AgentMessage_MessageIdentifier_name, int32(x))
}
func (x *AgentMessage_MessageIdentifier) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AgentMessage_MessageIdentifier_value, data, "AgentMessage_MessageIdentifier")
	if err != nil {
		return err
	}
	*x = AgentMessage_MessageIdentifier(value)
	return nil
}
func (AgentMessage_MessageIdentifier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0}
}

type AgentMessage_MessageType int32

const (
	AgentMessage_TYPE_ERROR         AgentMessage_MessageType = 1
	AgentMessage_TYPE_WARNING       AgentMessage_MessageType = 2
	AgentMessage_TYPE_INFORMATIONAL AgentMessage_MessageType = 3
)

var AgentMessage_MessageType_name = map[int32]string{
	1: "TYPE_ERROR",
	2: "TYPE_WARNING",
	3: "TYPE_INFORMATIONAL",
}
var AgentMessage_MessageType_value = map[string]int32{
	"TYPE_ERROR":         1,
	"TYPE_WARNING":       2,
	"TYPE_INFORMATIONAL": 3,
}

func (x AgentMessage_MessageType) Enum() *AgentMessage_MessageType {
	p := new(AgentMessage_MessageType)
	*p = x
	return p
}
func (x AgentMessage_MessageType) String() string {
	return proto.EnumName(AgentMessage_MessageType_name, int32(x))
}
func (x *AgentMessage_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AgentMessage_MessageType_value, data, "AgentMessage_MessageType")
	if err != nil {
		return err
	}
	*x = AgentMessage_MessageType(value)
	return nil
}
func (AgentMessage_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 1} }

// This message is used by agent to report operational error that the agent encountered.
// For example, if system inventory component cannot report hardware information because WMI is disabled, a MESSAGE_WMI_SERVICE_DISABLED message is sent to the server
type AgentMessage struct {
	// The UTC time that the message was produced by the agent. Time is what was reported by the client clock.
	TimeStamp *int64 `protobuf:"varint,1,req,name=timeStamp" json:"timeStamp,omitempty"`
	// The unique identifier of the agent. This field is used by the server to distinguish agents.
	AgentGUID  *string                         `protobuf:"bytes,2,req,name=agentGUID" json:"agentGUID,omitempty"`
	Identifier *AgentMessage_MessageIdentifier `protobuf:"varint,3,req,name=identifier,enum=AgentMessage_MessageIdentifier" json:"identifier,omitempty"`
	Type       *AgentMessage_MessageType       `protobuf:"varint,4,req,name=type,enum=AgentMessage_MessageType" json:"type,omitempty"`
	// Agent component producing the message
	Source *string `protobuf:"bytes,5,req,name=source" json:"source,omitempty"`
	// Message description
	Description *string `protobuf:"bytes,6,req,name=description" json:"description,omitempty"`
	SiteId      *string `protobuf:"bytes,7,opt,name=siteId" json:"siteId,omitempty"`
	Uuid        *string `protobuf:"bytes,8,opt,name=uuid" json:"uuid,omitempty"`
	// Numeric error value, if error
	ErrorValue       *int64 `protobuf:"varint,9,opt,name=errorValue,def=0" json:"errorValue,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AgentMessage) Reset()                    { *m = AgentMessage{} }
func (m *AgentMessage) String() string            { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()               {}
func (*AgentMessage) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

const Default_AgentMessage_ErrorValue int64 = 0

func (m *AgentMessage) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *AgentMessage) GetAgentGUID() string {
	if m != nil && m.AgentGUID != nil {
		return *m.AgentGUID
	}
	return ""
}

func (m *AgentMessage) GetIdentifier() AgentMessage_MessageIdentifier {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return AgentMessage_MESSAGE_SUCCESS
}

func (m *AgentMessage) GetType() AgentMessage_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return AgentMessage_TYPE_ERROR
}

func (m *AgentMessage) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *AgentMessage) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *AgentMessage) GetSiteId() string {
	if m != nil && m.SiteId != nil {
		return *m.SiteId
	}
	return ""
}

func (m *AgentMessage) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *AgentMessage) GetErrorValue() int64 {
	if m != nil && m.ErrorValue != nil {
		return *m.ErrorValue
	}
	return Default_AgentMessage_ErrorValue
}

func init() {
	proto.RegisterType((*AgentMessage)(nil), "AgentMessage")
	proto.RegisterEnum("AgentMessage_MessageIdentifier", AgentMessage_MessageIdentifier_name, AgentMessage_MessageIdentifier_value)
	proto.RegisterEnum("AgentMessage_MessageType", AgentMessage_MessageType_name, AgentMessage_MessageType_value)
}

var fileDescriptor3 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xcf, 0x6f, 0xd3, 0x30,
	0x18, 0xa5, 0x3f, 0xd6, 0xb5, 0xdf, 0xc6, 0xc8, 0x5c, 0x51, 0xc2, 0x00, 0x51, 0x7a, 0x00, 0xc4,
	0xa1, 0x42, 0x20, 0x0e, 0x70, 0x73, 0x12, 0x37, 0x58, 0x4b, 0x9c, 0xc9, 0x76, 0x3b, 0x71, 0x8a,
	0xaa, 0xd6, 0xab, 0x22, 0xad, 0x4d, 0x95, 0xa4, 0x48, 0x70, 0xe4, 0x0f, 0xe2, 0xc6, 0x5f, 0xc2,
	0x3f, 0x84, 0x9d, 0x36, 0x28, 0x13, 0x1c, 0x22, 0xe7, 0x7b, 0xef, 0xf9, 0x7b, 0xef, 0xb3, 0x0d,
	0x08, 0xaf, 0xd4, 0xa6, 0x08, 0x55, 0x9e, 0xcf, 0x57, 0x6a, 0xbc, 0xcd, 0xd2, 0x22, 0xbd, 0x40,
	0x57, 0x69, 0x5e, 0xac, 0x32, 0x95, 0xcb, 0x6f, 0xdb, 0x03, 0x36, 0xfa, 0x79, 0x04, 0xa7, 0x75,
	0x29, 0x1a, 0x42, 0xaf, 0x48, 0xd6, 0x4a, 0x14, 0xf3, 0xf5, 0xd6, 0x6e, 0x0c, 0x9b, 0xaf, 0x5b,
	0xce, 0xfd, 0x1f, 0xbf, 0xec, 0x12, 0xcc, 0x0d, 0x88, 0x9e, 0x40, 0x6f, 0x6e, 0x76, 0xf8, 0x53,
	0xea, 0xd9, 0x4d, 0xad, 0xe8, 0x39, 0x5d, 0xad, 0x68, 0xef, 0x76, 0xc9, 0x12, 0xbd, 0x07, 0x48,
	0x96, 0x9a, 0x4c, 0x6e, 0x12, 0x95, 0xd9, 0x2d, 0xcd, 0x9e, 0xbd, 0x7b, 0x3e, 0xbe, 0x13, 0xe6,
	0xb0, 0xd2, 0xbf, 0x32, 0xf4, 0x0a, 0xda, 0x85, 0x8e, 0x64, 0xb7, 0x4b, 0xf9, 0xe3, 0xff, 0xca,
	0x4d, 0x66, 0x74, 0x06, 0x9d, 0x3c, 0xdd, 0x65, 0x0b, 0x65, 0x1f, 0x19, 0x5f, 0xd4, 0x87, 0x93,
	0xa5, 0xca, 0x17, 0x59, 0xb2, 0x2d, 0x92, 0x74, 0x63, 0x77, 0x4a, 0xd0, 0x88, 0x92, 0x42, 0xf7,
	0xb7, 0x8f, 0x87, 0x0d, 0x5d, 0x0f, 0xa0, 0x8c, 0x66, 0x77, 0x4d, 0x55, 0x8b, 0xfa, 0x10, 0x40,
	0x65, 0x59, 0x9a, 0xcd, 0xe6, 0xb7, 0x3b, 0x65, 0xf7, 0x34, 0xdb, 0xfa, 0xd4, 0x78, 0x3b, 0xfa,
	0xdd, 0x84, 0xf3, 0x7f, 0x23, 0xf6, 0xe1, 0x41, 0x48, 0x84, 0xc0, 0x3e, 0x89, 0xc5, 0xd4, 0x75,
	0xf5, 0xaf, 0x75, 0x0f, 0x5d, 0xc0, 0xa0, 0x02, 0x27, 0x34, 0x20, 0x31, 0x8b, 0x64, 0x3c, 0x89,
	0xa6, 0xcc, 0xb3, 0x1a, 0xfa, 0x1c, 0x9f, 0x56, 0xdc, 0x75, 0x48, 0x63, 0x41, 0xf8, 0x8c, 0xba,
	0x24, 0xf6, 0xa8, 0xc0, 0x4e, 0x40, 0x3c, 0xab, 0xa9, 0xfd, 0xcf, 0xeb, 0x0a, 0xc2, 0x79, 0xc4,
	0xad, 0x16, 0x7a, 0x01, 0xcf, 0x2a, 0xd8, 0x0d, 0x28, 0x61, 0x52, 0xd2, 0x90, 0xb8, 0x41, 0xe4,
	0x5e, 0xba, 0x9f, 0x31, 0xf3, 0x89, 0xd5, 0xae, 0xfb, 0x3a, 0x3c, 0xba, 0x24, 0xdc, 0xc3, 0x12,
	0x07, 0x91, 0xce, 0x74, 0xa4, 0x6f, 0xe7, 0x51, 0xc5, 0x91, 0x99, 0xde, 0x1d, 0x44, 0xbe, 0x87,
	0x43, 0x5d, 0x7a, 0x56, 0x07, 0xbd, 0x81, 0x97, 0x15, 0xa9, 0x3f, 0x26, 0x85, 0xc4, 0x72, 0x2a,
	0x62, 0xe3, 0xc0, 0x75, 0x34, 0x6f, 0x3f, 0x01, 0xe5, 0xc4, 0x3a, 0xae, 0x6b, 0xcd, 0x70, 0x6e,
	0xc4, 0xa4, 0xd9, 0x11, 0x4b, 0x8e, 0x99, 0x08, 0xa9, 0x10, 0x34, 0x62, 0x71, 0x69, 0xda, 0xad,
	0x0f, 0x1b, 0x7a, 0x1f, 0x62, 0xdd, 0x9a, 0x70, 0x2c, 0x8d, 0x60, 0x3f, 0x55, 0x6f, 0xe4, 0xc3,
	0xc9, 0xdd, 0x8b, 0x04, 0xf9, 0xe5, 0x8a, 0x1c, 0xe8, 0x06, 0xb2, 0xe0, 0xb4, 0xac, 0xaf, 0x31,
	0x67, 0x94, 0xf9, 0xfa, 0x74, 0x06, 0x80, 0x4a, 0x84, 0xb2, 0x49, 0xc4, 0xc3, 0xb2, 0x19, 0x0e,
	0xac, 0x96, 0xf3, 0x11, 0x46, 0x8b, 0x74, 0x3d, 0xfe, 0x9e, 0xdc, 0x14, 0x6a, 0x33, 0xce, 0x55,
	0xf6, 0x55, 0x65, 0xfb, 0xb7, 0xbc, 0x48, 0x6f, 0xc7, 0xeb, 0xbd, 0x87, 0xd3, 0xaf, 0x3f, 0xa1,
	0xc3, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xaa, 0xb2, 0x26, 0x14, 0x03, 0x00, 0x00,
}
