// Code generated by protoc-gen-go.
// source: ExtensionRunResults.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Message indicating the results of an extension having been run
type ExtensionRunResults struct {
	// The standard fields
	// The time that the message was produced by the agent. Time is what was reported by the client clock.
	TimeStamp       *int64  `protobuf:"varint,1,req,name=timeStamp" json:"timeStamp,omitempty"`
	SiteId          *string `protobuf:"bytes,2,req,name=siteId" json:"siteId,omitempty"`
	ServerUUID      *string `protobuf:"bytes,3,opt,name=serverUUID" json:"serverUUID,omitempty"`
	ServerJobID     *int64  `protobuf:"varint,4,opt,name=serverJobID" json:"serverJobID,omitempty"`
	CorrelationUUID *string `protobuf:"bytes,5,opt,name=correlationUUID" json:"correlationUUID,omitempty"`
	AgentGUID       *string `protobuf:"bytes,6,req,name=agentGUID" json:"agentGUID,omitempty"`
	MessageVersion  *int32  `protobuf:"varint,7,opt,name=messageVersion,def=1" json:"messageVersion,omitempty"`
	// Distinctly identifies this extension object; used to refer to this particular script for various operations
	ExtensionUUID *string `protobuf:"bytes,8,opt,name=extensionUUID" json:"extensionUUID,omitempty"`
	// The UTC FILETIME that the script started running
	StartExecutionTimeStamp *int64 `protobuf:"varint,9,opt,name=startExecutionTimeStamp" json:"startExecutionTimeStamp,omitempty"`
	// The UTC FILETIME that the script finished running
	EndExecutionTimeStamp *int64 `protobuf:"varint,10,opt,name=endExecutionTimeStamp" json:"endExecutionTimeStamp,omitempty"`
	// 0-relative counter as records are produced per result set; allows preserving order
	SeqNo *int32 `protobuf:"varint,11,opt,name=seqNo" json:"seqNo,omitempty"`
	// process exit code from the extension's execution.  By long established convention, 0 means success.
	// Be wary of putting too much meaning on this; I have seen many failed script
	// exectutions return 0.  The programmer of the script must take care to code
	// the return values in a consistent and meaningful way.
	ExitCode *int32 `protobuf:"varint,12,opt,name=exitCode" json:"exitCode,omitempty"`
	// the first 1024 or so chars of stdout (and moreover only on the first
	// record of a result set).  In normal circumstances, this will be empty,
	// but it could be handy to provide some context in the event of field
	// problems.
	StdError *string `protobuf:"bytes,13,opt,name=stdError" json:"stdError,omitempty"`
	// 'event code' is a special (and required) return value from the script
	EventCode *int32 `protobuf:"varint,14,req,name=eventCode" json:"eventCode,omitempty"`
	// returned 'columns' of data;
	Tag0             *string `protobuf:"bytes,15,opt,name=tag0" json:"tag0,omitempty"`
	Tag1             *string `protobuf:"bytes,16,opt,name=tag1" json:"tag1,omitempty"`
	Tag2             *string `protobuf:"bytes,17,opt,name=tag2" json:"tag2,omitempty"`
	Tag3             *string `protobuf:"bytes,18,opt,name=tag3" json:"tag3,omitempty"`
	Tag4             *string `protobuf:"bytes,19,opt,name=tag4" json:"tag4,omitempty"`
	Tag5             *string `protobuf:"bytes,20,opt,name=tag5" json:"tag5,omitempty"`
	Tag6             *string `protobuf:"bytes,21,opt,name=tag6" json:"tag6,omitempty"`
	Tag7             *string `protobuf:"bytes,22,opt,name=tag7" json:"tag7,omitempty"`
	Tag8             *string `protobuf:"bytes,23,opt,name=tag8" json:"tag8,omitempty"`
	Tag9             *string `protobuf:"bytes,24,opt,name=tag9" json:"tag9,omitempty"`
	Tag10            *string `protobuf:"bytes,25,opt,name=tag10" json:"tag10,omitempty"`
	Tag11            *string `protobuf:"bytes,26,opt,name=tag11" json:"tag11,omitempty"`
	Tag12            *string `protobuf:"bytes,27,opt,name=tag12" json:"tag12,omitempty"`
	Tag13            *string `protobuf:"bytes,28,opt,name=tag13" json:"tag13,omitempty"`
	Tag14            *string `protobuf:"bytes,29,opt,name=tag14" json:"tag14,omitempty"`
	Tag15            *string `protobuf:"bytes,30,opt,name=tag15" json:"tag15,omitempty"`
	Tag16            *string `protobuf:"bytes,31,opt,name=tag16" json:"tag16,omitempty"`
	Tag17            *string `protobuf:"bytes,32,opt,name=tag17" json:"tag17,omitempty"`
	Tag18            *string `protobuf:"bytes,33,opt,name=tag18" json:"tag18,omitempty"`
	Tag19            *string `protobuf:"bytes,34,opt,name=tag19" json:"tag19,omitempty"`
	Uuid             *string `protobuf:"bytes,35,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExtensionRunResults) Reset()                    { *m = ExtensionRunResults{} }
func (m *ExtensionRunResults) String() string            { return proto.CompactTextString(m) }
func (*ExtensionRunResults) ProtoMessage()               {}
func (*ExtensionRunResults) Descriptor() ([]byte, []int) { return fileDescriptor24, []int{0} }

const Default_ExtensionRunResults_MessageVersion int32 = 1

func (m *ExtensionRunResults) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *ExtensionRunResults) GetSiteId() string {
	if m != nil && m.SiteId != nil {
		return *m.SiteId
	}
	return ""
}

func (m *ExtensionRunResults) GetServerUUID() string {
	if m != nil && m.ServerUUID != nil {
		return *m.ServerUUID
	}
	return ""
}

func (m *ExtensionRunResults) GetServerJobID() int64 {
	if m != nil && m.ServerJobID != nil {
		return *m.ServerJobID
	}
	return 0
}

func (m *ExtensionRunResults) GetCorrelationUUID() string {
	if m != nil && m.CorrelationUUID != nil {
		return *m.CorrelationUUID
	}
	return ""
}

func (m *ExtensionRunResults) GetAgentGUID() string {
	if m != nil && m.AgentGUID != nil {
		return *m.AgentGUID
	}
	return ""
}

func (m *ExtensionRunResults) GetMessageVersion() int32 {
	if m != nil && m.MessageVersion != nil {
		return *m.MessageVersion
	}
	return Default_ExtensionRunResults_MessageVersion
}

func (m *ExtensionRunResults) GetExtensionUUID() string {
	if m != nil && m.ExtensionUUID != nil {
		return *m.ExtensionUUID
	}
	return ""
}

func (m *ExtensionRunResults) GetStartExecutionTimeStamp() int64 {
	if m != nil && m.StartExecutionTimeStamp != nil {
		return *m.StartExecutionTimeStamp
	}
	return 0
}

func (m *ExtensionRunResults) GetEndExecutionTimeStamp() int64 {
	if m != nil && m.EndExecutionTimeStamp != nil {
		return *m.EndExecutionTimeStamp
	}
	return 0
}

func (m *ExtensionRunResults) GetSeqNo() int32 {
	if m != nil && m.SeqNo != nil {
		return *m.SeqNo
	}
	return 0
}

func (m *ExtensionRunResults) GetExitCode() int32 {
	if m != nil && m.ExitCode != nil {
		return *m.ExitCode
	}
	return 0
}

func (m *ExtensionRunResults) GetStdError() string {
	if m != nil && m.StdError != nil {
		return *m.StdError
	}
	return ""
}

func (m *ExtensionRunResults) GetEventCode() int32 {
	if m != nil && m.EventCode != nil {
		return *m.EventCode
	}
	return 0
}

func (m *ExtensionRunResults) GetTag0() string {
	if m != nil && m.Tag0 != nil {
		return *m.Tag0
	}
	return ""
}

func (m *ExtensionRunResults) GetTag1() string {
	if m != nil && m.Tag1 != nil {
		return *m.Tag1
	}
	return ""
}

func (m *ExtensionRunResults) GetTag2() string {
	if m != nil && m.Tag2 != nil {
		return *m.Tag2
	}
	return ""
}

func (m *ExtensionRunResults) GetTag3() string {
	if m != nil && m.Tag3 != nil {
		return *m.Tag3
	}
	return ""
}

func (m *ExtensionRunResults) GetTag4() string {
	if m != nil && m.Tag4 != nil {
		return *m.Tag4
	}
	return ""
}

func (m *ExtensionRunResults) GetTag5() string {
	if m != nil && m.Tag5 != nil {
		return *m.Tag5
	}
	return ""
}

func (m *ExtensionRunResults) GetTag6() string {
	if m != nil && m.Tag6 != nil {
		return *m.Tag6
	}
	return ""
}

func (m *ExtensionRunResults) GetTag7() string {
	if m != nil && m.Tag7 != nil {
		return *m.Tag7
	}
	return ""
}

func (m *ExtensionRunResults) GetTag8() string {
	if m != nil && m.Tag8 != nil {
		return *m.Tag8
	}
	return ""
}

func (m *ExtensionRunResults) GetTag9() string {
	if m != nil && m.Tag9 != nil {
		return *m.Tag9
	}
	return ""
}

func (m *ExtensionRunResults) GetTag10() string {
	if m != nil && m.Tag10 != nil {
		return *m.Tag10
	}
	return ""
}

func (m *ExtensionRunResults) GetTag11() string {
	if m != nil && m.Tag11 != nil {
		return *m.Tag11
	}
	return ""
}

func (m *ExtensionRunResults) GetTag12() string {
	if m != nil && m.Tag12 != nil {
		return *m.Tag12
	}
	return ""
}

func (m *ExtensionRunResults) GetTag13() string {
	if m != nil && m.Tag13 != nil {
		return *m.Tag13
	}
	return ""
}

func (m *ExtensionRunResults) GetTag14() string {
	if m != nil && m.Tag14 != nil {
		return *m.Tag14
	}
	return ""
}

func (m *ExtensionRunResults) GetTag15() string {
	if m != nil && m.Tag15 != nil {
		return *m.Tag15
	}
	return ""
}

func (m *ExtensionRunResults) GetTag16() string {
	if m != nil && m.Tag16 != nil {
		return *m.Tag16
	}
	return ""
}

func (m *ExtensionRunResults) GetTag17() string {
	if m != nil && m.Tag17 != nil {
		return *m.Tag17
	}
	return ""
}

func (m *ExtensionRunResults) GetTag18() string {
	if m != nil && m.Tag18 != nil {
		return *m.Tag18
	}
	return ""
}

func (m *ExtensionRunResults) GetTag19() string {
	if m != nil && m.Tag19 != nil {
		return *m.Tag19
	}
	return ""
}

func (m *ExtensionRunResults) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*ExtensionRunResults)(nil), "ExtensionRunResults")
}

var fileDescriptor24 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x95, 0x26, 0x2e, 0xf1, 0xb4, 0x49, 0xdb, 0x0d, 0x6d, 0x27, 0x69, 0xa1, 0x69, 0xb8,
	0xf4, 0x80, 0xac, 0xa6, 0xff, 0xcb, 0x09, 0x05, 0x22, 0x54, 0x24, 0x10, 0x2a, 0x2d, 0xf7, 0x60,
	0x0f, 0x91, 0xa5, 0xc4, 0x1b, 0x76, 0xd7, 0x55, 0xe0, 0xc8, 0x3b, 0xf1, 0x26, 0x3c, 0x10, 0xbb,
	0x6b, 0x82, 0xa6, 0x91, 0x8f, 0xbf, 0xf9, 0x66, 0x76, 0xe6, 0xd3, 0x7e, 0xd0, 0x1e, 0xce, 0x0d,
	0x65, 0x3a, 0x95, 0xd9, 0x6d, 0x9e, 0xdd, 0x92, 0xce, 0x27, 0x46, 0x47, 0x33, 0x25, 0x8d, 0xec,
	0x88, 0x4f, 0x52, 0x9b, 0xb1, 0x22, 0x7d, 0xf7, 0x63, 0x46, 0x45, 0xad, 0xf7, 0x27, 0x80, 0x56,
	0xc9, 0x84, 0xe8, 0x42, 0x68, 0xd2, 0x29, 0x7d, 0x36, 0xa3, 0xe9, 0x0c, 0x2b, 0xdd, 0x95, 0xa3,
	0xea, 0xa0, 0xf1, 0xeb, 0x37, 0xfa, 0xa2, 0x76, 0x45, 0xd1, 0x84, 0x55, 0x9d, 0x1a, 0xba, 0x49,
	0x70, 0xc5, 0xca, 0xa1, 0xd8, 0x07, 0xd0, 0xa4, 0x1e, 0x48, 0xdd, 0xdf, 0xdf, 0xbc, 0xc5, 0x6a,
	0xb7, 0x72, 0x14, 0x0e, 0xea, 0x76, 0xa4, 0x96, 0xe7, 0x69, 0x22, 0x5a, 0xb0, 0x56, 0xa8, 0xef,
	0xe5, 0x57, 0x2b, 0xd7, 0xac, 0x5c, 0x15, 0x87, 0xb0, 0x11, 0x4b, 0xa5, 0x68, 0x32, 0x32, 0x76,
	0xbb, 0x9f, 0x0b, 0x96, 0xe6, 0xf6, 0x20, 0x1c, 0x8d, 0x29, 0x33, 0xef, 0x9c, 0xb8, 0xea, 0x16,
	0x31, 0xb1, 0x0d, 0x4d, 0x7b, 0x8d, 0xb6, 0x0d, 0x5f, 0x48, 0x39, 0x03, 0xf8, 0xc4, 0x8e, 0x07,
	0xaf, 0x2a, 0x7d, 0x71, 0x00, 0x0d, 0x5a, 0xd8, 0xf2, 0x0f, 0xd7, 0x97, 0x1e, 0x8e, 0x60, 0xd7,
	0xfa, 0x50, 0x66, 0x38, 0xa7, 0x38, 0x77, 0xeb, 0xef, 0xfe, 0xdb, 0x0d, 0xdd, 0x71, 0xcb, 0x76,
	0x5f, 0xc2, 0x36, 0x65, 0x49, 0x49, 0x37, 0x94, 0x75, 0x37, 0x20, 0xd0, 0xf4, 0xfd, 0xa3, 0xc4,
	0x35, 0x77, 0x90, 0xd8, 0x84, 0x3a, 0xcd, 0x53, 0xf3, 0x46, 0x26, 0x84, 0xeb, 0x8b, 0x8a, 0x36,
	0xc9, 0x50, 0x29, 0xa9, 0xb0, 0xe1, 0x4e, 0x13, 0x5b, 0x10, 0xd2, 0x83, 0x75, 0xea, 0x9b, 0x9a,
	0xd6, 0x69, 0x20, 0xd6, 0xa1, 0x66, 0x46, 0xe3, 0x63, 0xdc, 0xf0, 0x0d, 0x05, 0xf5, 0x71, 0x93,
	0xd1, 0x09, 0x6e, 0x31, 0x3a, 0x45, 0xc1, 0xe8, 0x0c, 0x5b, 0x8c, 0xce, 0xf1, 0x29, 0xa3, 0x0b,
	0xdc, 0x66, 0x74, 0x89, 0x3b, 0x8c, 0xae, 0x70, 0x97, 0xd1, 0x35, 0xa2, 0x27, 0xeb, 0xc8, 0x6d,
	0x3f, 0xc6, 0x36, 0xc7, 0x3e, 0x76, 0x38, 0x9e, 0xe0, 0x1e, 0xc7, 0x53, 0xdc, 0xe7, 0x78, 0x86,
	0xcf, 0x38, 0x9e, 0xe3, 0x73, 0x8e, 0x17, 0x78, 0xc0, 0xf1, 0x12, 0xbb, 0x1c, 0xaf, 0xf0, 0x90,
	0xe3, 0x35, 0xf6, 0x3c, 0xee, 0x80, 0xff, 0x4d, 0x7c, 0xf1, 0xf8, 0x77, 0x07, 0xaf, 0xa1, 0x17,
	0xcb, 0x69, 0xf4, 0x33, 0xfd, 0x66, 0x33, 0x10, 0x15, 0xc9, 0x2b, 0x12, 0x1f, 0xcb, 0x49, 0xf4,
	0x2f, 0x34, 0x83, 0x4e, 0x49, 0xf2, 0x3f, 0x14, 0xda, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75,
	0xf3, 0x6c, 0x63, 0x48, 0x03, 0x00, 0x00,
}
