// Code generated by protoc-gen-go.
// source: GenericServerMonitor.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GenericServerMonitor struct {
	TimeStamp        *int64  `protobuf:"varint,1,req,name=timeStamp" json:"timeStamp,omitempty"`
	AgentGUID        *string `protobuf:"bytes,2,req,name=agentGUID" json:"agentGUID,omitempty"`
	SiteId           *string `protobuf:"bytes,3,opt,name=siteId" json:"siteId,omitempty"`
	Logfile          *string `protobuf:"bytes,4,req,name=logfile" json:"logfile,omitempty"`
	Severity         *int32  `protobuf:"varint,5,req,name=severity" json:"severity,omitempty"`
	EventId          *string `protobuf:"bytes,6,req,name=eventId" json:"eventId,omitempty"`
	Tag0             *string `protobuf:"bytes,7,opt,name=tag0" json:"tag0,omitempty"`
	Tag1             *string `protobuf:"bytes,8,opt,name=tag1" json:"tag1,omitempty"`
	Tag2             *string `protobuf:"bytes,9,opt,name=tag2" json:"tag2,omitempty"`
	Tag3             *string `protobuf:"bytes,10,opt,name=tag3" json:"tag3,omitempty"`
	Tag4             *string `protobuf:"bytes,11,opt,name=tag4" json:"tag4,omitempty"`
	Tag5             *string `protobuf:"bytes,12,opt,name=tag5" json:"tag5,omitempty"`
	Tag6             *string `protobuf:"bytes,13,opt,name=tag6" json:"tag6,omitempty"`
	Tag7             *string `protobuf:"bytes,14,opt,name=tag7" json:"tag7,omitempty"`
	Tag8             *string `protobuf:"bytes,15,opt,name=tag8" json:"tag8,omitempty"`
	Tag9             *string `protobuf:"bytes,16,opt,name=tag9" json:"tag9,omitempty"`
	Uuid             *string `protobuf:"bytes,17,opt,name=uuid" json:"uuid,omitempty"`
	Tag10            *string `protobuf:"bytes,18,opt,name=tag10" json:"tag10,omitempty"`
	Tag11            *string `protobuf:"bytes,19,opt,name=tag11" json:"tag11,omitempty"`
	Tag12            *string `protobuf:"bytes,20,opt,name=tag12" json:"tag12,omitempty"`
	Tag13            *string `protobuf:"bytes,21,opt,name=tag13" json:"tag13,omitempty"`
	Tag14            *string `protobuf:"bytes,22,opt,name=tag14" json:"tag14,omitempty"`
	Tag15            *string `protobuf:"bytes,23,opt,name=tag15" json:"tag15,omitempty"`
	Tag16            *string `protobuf:"bytes,24,opt,name=tag16" json:"tag16,omitempty"`
	Tag17            *string `protobuf:"bytes,25,opt,name=tag17" json:"tag17,omitempty"`
	Tag18            *string `protobuf:"bytes,26,opt,name=tag18" json:"tag18,omitempty"`
	Tag19            *string `protobuf:"bytes,27,opt,name=tag19" json:"tag19,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenericServerMonitor) Reset()                    { *m = GenericServerMonitor{} }
func (m *GenericServerMonitor) String() string            { return proto.CompactTextString(m) }
func (*GenericServerMonitor) ProtoMessage()               {}
func (*GenericServerMonitor) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{0} }

func (m *GenericServerMonitor) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *GenericServerMonitor) GetAgentGUID() string {
	if m != nil && m.AgentGUID != nil {
		return *m.AgentGUID
	}
	return ""
}

func (m *GenericServerMonitor) GetSiteId() string {
	if m != nil && m.SiteId != nil {
		return *m.SiteId
	}
	return ""
}

func (m *GenericServerMonitor) GetLogfile() string {
	if m != nil && m.Logfile != nil {
		return *m.Logfile
	}
	return ""
}

func (m *GenericServerMonitor) GetSeverity() int32 {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return 0
}

func (m *GenericServerMonitor) GetEventId() string {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return ""
}

func (m *GenericServerMonitor) GetTag0() string {
	if m != nil && m.Tag0 != nil {
		return *m.Tag0
	}
	return ""
}

func (m *GenericServerMonitor) GetTag1() string {
	if m != nil && m.Tag1 != nil {
		return *m.Tag1
	}
	return ""
}

func (m *GenericServerMonitor) GetTag2() string {
	if m != nil && m.Tag2 != nil {
		return *m.Tag2
	}
	return ""
}

func (m *GenericServerMonitor) GetTag3() string {
	if m != nil && m.Tag3 != nil {
		return *m.Tag3
	}
	return ""
}

func (m *GenericServerMonitor) GetTag4() string {
	if m != nil && m.Tag4 != nil {
		return *m.Tag4
	}
	return ""
}

func (m *GenericServerMonitor) GetTag5() string {
	if m != nil && m.Tag5 != nil {
		return *m.Tag5
	}
	return ""
}

func (m *GenericServerMonitor) GetTag6() string {
	if m != nil && m.Tag6 != nil {
		return *m.Tag6
	}
	return ""
}

func (m *GenericServerMonitor) GetTag7() string {
	if m != nil && m.Tag7 != nil {
		return *m.Tag7
	}
	return ""
}

func (m *GenericServerMonitor) GetTag8() string {
	if m != nil && m.Tag8 != nil {
		return *m.Tag8
	}
	return ""
}

func (m *GenericServerMonitor) GetTag9() string {
	if m != nil && m.Tag9 != nil {
		return *m.Tag9
	}
	return ""
}

func (m *GenericServerMonitor) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *GenericServerMonitor) GetTag10() string {
	if m != nil && m.Tag10 != nil {
		return *m.Tag10
	}
	return ""
}

func (m *GenericServerMonitor) GetTag11() string {
	if m != nil && m.Tag11 != nil {
		return *m.Tag11
	}
	return ""
}

func (m *GenericServerMonitor) GetTag12() string {
	if m != nil && m.Tag12 != nil {
		return *m.Tag12
	}
	return ""
}

func (m *GenericServerMonitor) GetTag13() string {
	if m != nil && m.Tag13 != nil {
		return *m.Tag13
	}
	return ""
}

func (m *GenericServerMonitor) GetTag14() string {
	if m != nil && m.Tag14 != nil {
		return *m.Tag14
	}
	return ""
}

func (m *GenericServerMonitor) GetTag15() string {
	if m != nil && m.Tag15 != nil {
		return *m.Tag15
	}
	return ""
}

func (m *GenericServerMonitor) GetTag16() string {
	if m != nil && m.Tag16 != nil {
		return *m.Tag16
	}
	return ""
}

func (m *GenericServerMonitor) GetTag17() string {
	if m != nil && m.Tag17 != nil {
		return *m.Tag17
	}
	return ""
}

func (m *GenericServerMonitor) GetTag18() string {
	if m != nil && m.Tag18 != nil {
		return *m.Tag18
	}
	return ""
}

func (m *GenericServerMonitor) GetTag19() string {
	if m != nil && m.Tag19 != nil {
		return *m.Tag19
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericServerMonitor)(nil), "GenericServerMonitor")
}

var fileDescriptor27 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0xd1, 0xcb, 0x6a, 0x02, 0x31,
	0x18, 0x05, 0x60, 0xbc, 0x3b, 0xa9, 0xb7, 0xa6, 0xd6, 0x9e, 0xea, 0x46, 0x5c, 0xb9, 0x1a, 0xbc,
	0x5f, 0x96, 0x95, 0x82, 0xb8, 0x10, 0x0a, 0xb6, 0x0f, 0x20, 0x1a, 0x87, 0x80, 0x4e, 0x64, 0x12,
	0x0b, 0x76, 0xd9, 0x77, 0xea, 0x93, 0xf4, 0x85, 0x9a, 0xc9, 0x74, 0xf1, 0x2f, 0x5c, 0x7e, 0xc7,
	0x13, 0x27, 0xe1, 0xb0, 0xe6, 0x52, 0x84, 0x22, 0x92, 0xbb, 0x8d, 0x88, 0x3e, 0x45, 0xb4, 0x56,
	0xa1, 0x34, 0x2a, 0xf2, 0xcf, 0x91, 0x32, 0xaa, 0xc9, 0xdf, 0x94, 0x36, 0x41, 0x24, 0xf4, 0xfb,
	0xf5, 0x2c, 0x92, 0xac, 0xf3, 0x9b, 0x61, 0xf5, 0x5b, 0x47, 0x78, 0x9b, 0x79, 0x46, 0x9e, 0xc4,
	0xc6, 0x6c, 0x4f, 0x67, 0xa4, 0xda, 0xe9, 0x6e, 0x66, 0x51, 0xfe, 0xfe, 0x81, 0x0b, 0x75, 0x1c,
	0xf2, 0x16, 0xf3, 0xb6, 0x81, 0x08, 0xcd, 0xf2, 0x63, 0xf5, 0x8a, 0xb4, 0x6d, 0x78, 0x8b, 0xa2,
	0x6d, 0x64, 0x2f, 0x17, 0xb9, 0xe7, 0x15, 0x96, 0xd7, 0xd2, 0x88, 0xd5, 0x1e, 0x99, 0x76, 0xaa,
	0xeb, 0xf1, 0x2a, 0x2b, 0x1c, 0x55, 0x70, 0x90, 0x47, 0x81, 0x6c, 0x5c, 0xe5, 0x35, 0x56, 0xd4,
	0xc2, 0x7e, 0x4f, 0x9a, 0x2b, 0x72, 0x36, 0xc9, 0xc5, 0x15, 0x1b, 0x84, 0xc6, 0x9e, 0xc9, 0xbb,
	0x4a, 0x89, 0x65, 0xcd, 0x36, 0xe8, 0xa1, 0xe0, 0xfe, 0x21, 0x51, 0x1f, 0x45, 0xa2, 0x01, 0x3c,
	0xa2, 0x21, 0x18, 0xd1, 0x08, 0x77, 0x44, 0x63, 0x94, 0x88, 0x26, 0x28, 0x13, 0x4d, 0x51, 0x21,
	0x9a, 0xa1, 0x4a, 0x34, 0x47, 0xcd, 0xa9, 0xc1, 0xdc, 0xbb, 0x70, 0x1f, 0x8b, 0xbc, 0xb3, 0xcc,
	0x72, 0xf1, 0xad, 0x7a, 0xe0, 0xae, 0xf6, 0xcf, 0x3e, 0x1e, 0x28, 0x07, 0xa8, 0x53, 0x0e, 0xf1,
	0x48, 0x39, 0x42, 0x83, 0x72, 0x8c, 0x27, 0xca, 0x09, 0x40, 0x39, 0xc5, 0x33, 0xe5, 0x0c, 0x4d,
	0xca, 0x39, 0x5a, 0xee, 0x7e, 0x2f, 0xac, 0xb3, 0x53, 0x27, 0xff, 0x4b, 0x1e, 0x8c, 0x08, 0x7d,
	0xed, 0x86, 0x4d, 0x06, 0xdf, 0xa9, 0xa3, 0x6f, 0x07, 0xd4, 0x76, 0xb9, 0x45, 0xeb, 0xd6, 0xf0,
	0xeb, 0xe4, 0xc7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x8d, 0x59, 0xfb, 0x49, 0x02, 0x00,
	0x00,
}
