// Code generated by protoc-gen-go.
// source: AgentSettingsResponse.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Platform independent return code of the executed command.
type AgentSettingsResponse_AgentSettingsResult int32

const (
	AgentSettingsResponse_AGENTSETTINGS_SUCCESS AgentSettingsResponse_AgentSettingsResult = 0
	AgentSettingsResponse_AGENTSETTINGS_FAILURE AgentSettingsResponse_AgentSettingsResult = 1
)

var AgentSettingsResponse_AgentSettingsResult_name = map[int32]string{
	0: "AGENTSETTINGS_SUCCESS",
	1: "AGENTSETTINGS_FAILURE",
}
var AgentSettingsResponse_AgentSettingsResult_value = map[string]int32{
	"AGENTSETTINGS_SUCCESS": 0,
	"AGENTSETTINGS_FAILURE": 1,
}

func (x AgentSettingsResponse_AgentSettingsResult) Enum() *AgentSettingsResponse_AgentSettingsResult {
	p := new(AgentSettingsResponse_AgentSettingsResult)
	*p = x
	return p
}
func (x AgentSettingsResponse_AgentSettingsResult) String() string {
	return proto1.EnumName(AgentSettingsResponse_AgentSettingsResult_name, int32(x))
}
func (x *AgentSettingsResponse_AgentSettingsResult) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(AgentSettingsResponse_AgentSettingsResult_value, data, "AgentSettingsResponse_AgentSettingsResult")
	if err != nil {
		return err
	}
	*x = AgentSettingsResponse_AgentSettingsResult(value)
	return nil
}
func (AgentSettingsResponse_AgentSettingsResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 0}
}

// Message informing the server about the outcome of a AgentSettings request
type AgentSettingsResponse struct {
	// The time that the message was produced by the agent. Time is what was reported by the client clock.
	TimeStamp *int64 `protobuf:"varint,1,req,name=timeStamp" json:"timeStamp,omitempty"`
	// The unique identifier of the agent. This field is used by the server to distinguish agents.
	AgentGUID *string `protobuf:"bytes,2,req,name=agentGUID" json:"agentGUID,omitempty"`
	// This is the jobID from the server, passed back so we know which setting message was applied
	ServerJobID      *int64                                     `protobuf:"varint,3,opt,name=serverJobID" json:"serverJobID,omitempty"`
	SettingsResult   *AgentSettingsResponse_AgentSettingsResult `protobuf:"varint,4,req,name=settingsResult,enum=AgentSettingsResponse_AgentSettingsResult" json:"settingsResult,omitempty"`
	SiteId           *string                                    `protobuf:"bytes,5,opt,name=siteId" json:"siteId,omitempty"`
	Uuid             *string                                    `protobuf:"bytes,6,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte                                     `json:"-"`
}

func (m *AgentSettingsResponse) Reset()                    { *m = AgentSettingsResponse{} }
func (m *AgentSettingsResponse) String() string            { return proto1.CompactTextString(m) }
func (*AgentSettingsResponse) ProtoMessage()               {}
func (*AgentSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *AgentSettingsResponse) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *AgentSettingsResponse) GetAgentGUID() string {
	if m != nil && m.AgentGUID != nil {
		return *m.AgentGUID
	}
	return ""
}

func (m *AgentSettingsResponse) GetServerJobID() int64 {
	if m != nil && m.ServerJobID != nil {
		return *m.ServerJobID
	}
	return 0
}

func (m *AgentSettingsResponse) GetSettingsResult() AgentSettingsResponse_AgentSettingsResult {
	if m != nil && m.SettingsResult != nil {
		return *m.SettingsResult
	}
	return AgentSettingsResponse_AGENTSETTINGS_SUCCESS
}

func (m *AgentSettingsResponse) GetSiteId() string {
	if m != nil && m.SiteId != nil {
		return *m.SiteId
	}
	return ""
}

func (m *AgentSettingsResponse) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func init() {
	proto1.RegisterType((*AgentSettingsResponse)(nil), "AgentSettingsResponse")
	proto1.RegisterEnum("AgentSettingsResponse_AgentSettingsResult", AgentSettingsResponse_AgentSettingsResult_name, AgentSettingsResponse_AgentSettingsResult_value)
}

var fileDescriptor5 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4e, 0x83, 0x40,
	0x14, 0x85, 0x05, 0x6a, 0x23, 0x63, 0x24, 0xcd, 0x34, 0x9a, 0xd1, 0xba, 0x20, 0xac, 0x1a, 0x17,
	0x2c, 0x7c, 0x83, 0x4e, 0x45, 0x82, 0x3f, 0x8d, 0xe9, 0xc0, 0xda, 0xd4, 0x76, 0x24, 0x93, 0x14,
	0x86, 0x70, 0x2f, 0x26, 0xba, 0xf4, 0x59, 0x7c, 0x05, 0xdf, 0xcf, 0xa1, 0x98, 0x34, 0x51, 0x96,
	0x73, 0xce, 0xfd, 0xe6, 0xde, 0x73, 0xc8, 0x64, 0x96, 0xcb, 0x12, 0x85, 0x44, 0x54, 0x65, 0x0e,
	0x4b, 0x09, 0x95, 0x2e, 0x41, 0x86, 0x55, 0xad, 0x51, 0x5f, 0xd0, 0x27, 0x0d, 0x98, 0xd7, 0x12,
	0xd2, 0xf7, 0xea, 0x57, 0x0b, 0xbe, 0x6c, 0x72, 0xda, 0xcb, 0x50, 0x9f, 0xb8, 0xa8, 0x0a, 0x29,
	0x70, 0x55, 0x54, 0xcc, 0xf2, 0xed, 0xa9, 0xc3, 0x4f, 0x3e, 0xbf, 0xd9, 0x4e, 0x84, 0x56, 0xa4,
	0x13, 0xe2, 0xae, 0x5a, 0x34, 0xce, 0x92, 0x1b, 0x66, 0x9b, 0x09, 0x97, 0x1f, 0x99, 0x89, 0x41,
	0xd3, 0xa8, 0x0d, 0x1d, 0x93, 0x63, 0x90, 0xf5, 0x9b, 0xac, 0xef, 0xf4, 0x8b, 0xb1, 0x1d, 0xdf,
	0x9a, 0x3a, 0x94, 0x13, 0x0f, 0xf6, 0x7b, 0x9a, 0x2d, 0xb2, 0x81, 0xc1, 0xbc, 0xeb, 0xab, 0xb0,
	0xff, 0xee, 0xbf, 0xaa, 0x21, 0xa8, 0x47, 0x86, 0xa0, 0x50, 0x26, 0x1b, 0x76, 0x68, 0xfe, 0x74,
	0xe9, 0x19, 0xd9, 0x2d, 0x64, 0xc3, 0xf6, 0xb5, 0x3f, 0x20, 0xb8, 0x27, 0xe3, 0x3e, 0xfc, 0xdc,
	0xe4, 0x8d, 0xa3, 0x45, 0x2a, 0xa2, 0x34, 0x4d, 0x16, 0xb1, 0x78, 0x16, 0xd9, 0x7c, 0x1e, 0x09,
	0x31, 0x3a, 0xf8, 0x6f, 0xdd, 0xce, 0x92, 0x87, 0x6c, 0x19, 0x8d, 0x2c, 0xce, 0x49, 0xb0, 0xd6,
	0x45, 0xf8, 0xa1, 0x5e, 0x51, 0x96, 0x61, 0x17, 0xac, 0x6b, 0x70, 0xad, 0xb7, 0xa1, 0x29, 0x04,
	0x4c, 0x13, 0xfc, 0xb2, 0x37, 0xc5, 0x63, 0xe7, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x1e,
	0x1a, 0x28, 0x9c, 0x01, 0x00, 0x00,
}
