// Code generated by protoc-gen-go.
// source: OSXAgentCommandResponse.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Platform independent return code of the executed command.
type OSXAgentCommandResponse_CommandResult int32

const (
	OSXAgentCommandResponse_COMMAND_SUCCESS OSXAgentCommandResponse_CommandResult = 0
	OSXAgentCommandResponse_COMMAND_FAILURE OSXAgentCommandResponse_CommandResult = 1
)

var OSXAgentCommandResponse_CommandResult_name = map[int32]string{
	0: "COMMAND_SUCCESS",
	1: "COMMAND_FAILURE",
}
var OSXAgentCommandResponse_CommandResult_value = map[string]int32{
	"COMMAND_SUCCESS": 0,
	"COMMAND_FAILURE": 1,
}

func (x OSXAgentCommandResponse_CommandResult) Enum() *OSXAgentCommandResponse_CommandResult {
	p := new(OSXAgentCommandResponse_CommandResult)
	*p = x
	return p
}
func (x OSXAgentCommandResponse_CommandResult) String() string {
	return proto1.EnumName(OSXAgentCommandResponse_CommandResult_name, int32(x))
}
func (x *OSXAgentCommandResponse_CommandResult) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(OSXAgentCommandResponse_CommandResult_value, data, "OSXAgentCommandResponse_CommandResult")
	if err != nil {
		return err
	}
	*x = OSXAgentCommandResponse_CommandResult(value)
	return nil
}
func (OSXAgentCommandResponse_CommandResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor41, []int{0, 0}
}

// Added for FileContents command, to give reason for failure
type OSXAgentCommandResponse_FailureCode int32

const (
	OSXAgentCommandResponse_FAIL_NO_ERROR       OSXAgentCommandResponse_FailureCode = 0
	OSXAgentCommandResponse_FAIL_MISSING_FILE   OSXAgentCommandResponse_FailureCode = 1
	OSXAgentCommandResponse_FAIL_FILE_TOO_LARGE OSXAgentCommandResponse_FailureCode = 2
	OSXAgentCommandResponse_FAIL_ACCESS_DENIED  OSXAgentCommandResponse_FailureCode = 3
	OSXAgentCommandResponse_FAIL_FILE_OPERATION OSXAgentCommandResponse_FailureCode = 4
)

var OSXAgentCommandResponse_FailureCode_name = map[int32]string{
	0: "FAIL_NO_ERROR",
	1: "FAIL_MISSING_FILE",
	2: "FAIL_FILE_TOO_LARGE",
	3: "FAIL_ACCESS_DENIED",
	4: "FAIL_FILE_OPERATION",
}
var OSXAgentCommandResponse_FailureCode_value = map[string]int32{
	"FAIL_NO_ERROR":       0,
	"FAIL_MISSING_FILE":   1,
	"FAIL_FILE_TOO_LARGE": 2,
	"FAIL_ACCESS_DENIED":  3,
	"FAIL_FILE_OPERATION": 4,
}

func (x OSXAgentCommandResponse_FailureCode) Enum() *OSXAgentCommandResponse_FailureCode {
	p := new(OSXAgentCommandResponse_FailureCode)
	*p = x
	return p
}
func (x OSXAgentCommandResponse_FailureCode) String() string {
	return proto1.EnumName(OSXAgentCommandResponse_FailureCode_name, int32(x))
}
func (x *OSXAgentCommandResponse_FailureCode) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(OSXAgentCommandResponse_FailureCode_value, data, "OSXAgentCommandResponse_FailureCode")
	if err != nil {
		return err
	}
	*x = OSXAgentCommandResponse_FailureCode(value)
	return nil
}
func (OSXAgentCommandResponse_FailureCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor41, []int{0, 1}
}

// Message informing the server about the outcome of a command request
type OSXAgentCommandResponse struct {
	// The time that the message was produced by the agent. Time is what was reported by the client clock.
	TimeStamp *int64 `protobuf:"varint,1,req,name=timeStamp" json:"timeStamp,omitempty"`
	// The unique identifier of the agent. This field is used by the server to distinguish agents.
	AgentGUID *string `protobuf:"bytes,2,req,name=agentGUID" json:"agentGUID,omitempty"`
	// The server assigns a command identifier to all command jobs
	// The agent will return the identifier in the command response
	CommandIdentifier *uint64                                `protobuf:"varint,3,req,name=commandIdentifier" json:"commandIdentifier,omitempty"`
	CommandResult     *OSXAgentCommandResponse_CommandResult `protobuf:"varint,4,req,name=commandResult,enum=OSXAgentCommandResponse_CommandResult" json:"commandResult,omitempty"`
	SiteId            *string                                `protobuf:"bytes,5,opt,name=siteId" json:"siteId,omitempty"`
	Uuid              *string                                `protobuf:"bytes,6,opt,name=uuid" json:"uuid,omitempty"`
	FailCode          *OSXAgentCommandResponse_FailureCode   `protobuf:"varint,7,opt,name=failCode,enum=OSXAgentCommandResponse_FailureCode" json:"failCode,omitempty"`
	XXX_unrecognized  []byte                                 `json:"-"`
}

func (m *OSXAgentCommandResponse) Reset()                    { *m = OSXAgentCommandResponse{} }
func (m *OSXAgentCommandResponse) String() string            { return proto1.CompactTextString(m) }
func (*OSXAgentCommandResponse) ProtoMessage()               {}
func (*OSXAgentCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor41, []int{0} }

func (m *OSXAgentCommandResponse) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *OSXAgentCommandResponse) GetAgentGUID() string {
	if m != nil && m.AgentGUID != nil {
		return *m.AgentGUID
	}
	return ""
}

func (m *OSXAgentCommandResponse) GetCommandIdentifier() uint64 {
	if m != nil && m.CommandIdentifier != nil {
		return *m.CommandIdentifier
	}
	return 0
}

func (m *OSXAgentCommandResponse) GetCommandResult() OSXAgentCommandResponse_CommandResult {
	if m != nil && m.CommandResult != nil {
		return *m.CommandResult
	}
	return OSXAgentCommandResponse_COMMAND_SUCCESS
}

func (m *OSXAgentCommandResponse) GetSiteId() string {
	if m != nil && m.SiteId != nil {
		return *m.SiteId
	}
	return ""
}

func (m *OSXAgentCommandResponse) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *OSXAgentCommandResponse) GetFailCode() OSXAgentCommandResponse_FailureCode {
	if m != nil && m.FailCode != nil {
		return *m.FailCode
	}
	return OSXAgentCommandResponse_FAIL_NO_ERROR
}

func init() {
	proto1.RegisterType((*OSXAgentCommandResponse)(nil), "OSXAgentCommandResponse")
	proto1.RegisterEnum("OSXAgentCommandResponse_CommandResult", OSXAgentCommandResponse_CommandResult_name, OSXAgentCommandResponse_CommandResult_value)
	proto1.RegisterEnum("OSXAgentCommandResponse_FailureCode", OSXAgentCommandResponse_FailureCode_name, OSXAgentCommandResponse_FailureCode_value)
}

var fileDescriptor41 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xcf, 0xaa, 0xd3, 0x40,
	0x18, 0xc5, 0x4d, 0x13, 0xaf, 0x37, 0x9f, 0xa4, 0xa6, 0x73, 0xd1, 0x3b, 0x2a, 0x4a, 0x09, 0x22,
	0x77, 0x95, 0xc5, 0x5d, 0x08, 0x2e, 0x5c, 0xe4, 0x5f, 0xcb, 0x40, 0x93, 0x29, 0x49, 0x0b, 0xee,
	0x42, 0x68, 0xa6, 0x25, 0xd0, 0xfc, 0x21, 0x33, 0x11, 0x74, 0xa7, 0xef, 0xe4, 0x83, 0xf8, 0x46,
	0x4e, 0x52, 0x91, 0x74, 0x91, 0xe5, 0x9c, 0xf3, 0x3b, 0x73, 0x66, 0xbe, 0x0f, 0xde, 0xd1, 0xe4,
	0xab, 0x73, 0x62, 0x95, 0xf0, 0xea, 0xb2, 0xcc, 0xaa, 0x3c, 0x66, 0xbc, 0xa9, 0x2b, 0xce, 0xec,
	0xa6, 0xad, 0x45, 0xfd, 0x06, 0x6d, 0x6b, 0x2e, 0x4e, 0x2d, 0xe3, 0xbb, 0xef, 0xcd, 0x3f, 0xcd,
	0xfa, 0xa3, 0xc2, 0xfd, 0x44, 0x0a, 0x2d, 0x41, 0x17, 0x45, 0xc9, 0x12, 0x91, 0x95, 0x0d, 0x56,
	0x96, 0xb3, 0x07, 0xd5, 0x35, 0x7e, 0xfd, 0xc6, 0x83, 0xc8, 0x7b, 0x11, 0xbd, 0x05, 0x3d, 0xeb,
	0x93, 0xeb, 0x3d, 0xf1, 0xf1, 0x4c, 0x12, 0xba, 0x7b, 0x2b, 0x09, 0xad, 0xeb, 0x8a, 0x1c, 0xbd,
	0x86, 0xc5, 0xe1, 0x72, 0x23, 0xc9, 0x25, 0x53, 0x1c, 0x0b, 0xd6, 0x62, 0x55, 0x42, 0x1a, 0xfa,
	0x02, 0xc6, 0xe1, 0x7f, 0x59, 0x77, 0x16, 0x58, 0x93, 0xf2, 0xfc, 0xf1, 0xa3, 0x3d, 0xf5, 0x01,
	0x6f, 0x4c, 0xa3, 0x39, 0xdc, 0xf0, 0x42, 0x30, 0x92, 0xe3, 0xa7, 0x4b, 0xe5, 0x41, 0x47, 0xaf,
	0x60, 0x68, 0xc4, 0x37, 0xfd, 0x69, 0xf4, 0x82, 0x4f, 0x70, 0x7b, 0xcc, 0x8a, 0xb3, 0x57, 0xe7,
	0x0c, 0x3f, 0x93, 0xde, 0xfc, 0xf1, 0xc3, 0x64, 0xc3, 0x4a, 0x82, 0x5d, 0xcb, 0x7a, 0xd6, 0xfa,
	0x0c, 0xc6, 0x75, 0xe1, 0x1d, 0xbc, 0xf0, 0x68, 0x18, 0x3a, 0x91, 0x9f, 0x26, 0x7b, 0xcf, 0x0b,
	0x92, 0xc4, 0x7c, 0x32, 0x16, 0x57, 0x0e, 0xd9, 0xec, 0xe3, 0xc0, 0x54, 0xac, 0x9f, 0x0a, 0x3c,
	0x1f, 0x5d, 0x85, 0x16, 0x60, 0xf4, 0x66, 0x1a, 0xd1, 0x34, 0x88, 0x63, 0x1a, 0xcb, 0xdc, 0x4b,
	0x58, 0x0c, 0x52, 0x48, 0x92, 0x84, 0x44, 0xeb, 0x74, 0x45, 0x36, 0x32, 0x89, 0xee, 0xe1, 0x6e,
	0x90, 0xfb, 0x63, 0xba, 0xa3, 0x34, 0xdd, 0x38, 0xf1, 0x3a, 0x30, 0x67, 0xf2, 0x77, 0x68, 0x30,
	0x9c, 0xa1, 0x38, 0xf5, 0x83, 0x88, 0x04, 0xbe, 0xa9, 0x5e, 0x07, 0xe8, 0x36, 0x88, 0x9d, 0x1d,
	0xa1, 0x91, 0xa9, 0xb9, 0x3e, 0x58, 0x72, 0xba, 0xf6, 0x8f, 0xe2, 0x28, 0x58, 0x65, 0x73, 0xd6,
	0x7e, 0x63, 0xed, 0x65, 0xdd, 0x87, 0xfa, 0x6c, 0xcb, 0xdd, 0x71, 0xb9, 0x34, 0xf7, 0xfd, 0xc4,
	0x24, 0xc2, 0x8b, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x61, 0x9a, 0xac, 0x39, 0x4d, 0x02, 0x00,
	0x00,
}
