// Code generated by protoc-gen-go.
// source: OSXBootAnalysis.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Report information read from Global Logger Boot Trace after a boot occurred
type OSXBootAnalysis struct {
	// The UTC time that the message was produced by the agent. Time is what was reported by the client clock.
	TimeStamp *int64 `protobuf:"varint,1,req,name=timeStamp" json:"timeStamp,omitempty"`
	// The unique identifier of the agent. This field is used by the server to distinguish agents.
	AgentGUID    *string `protobuf:"bytes,2,req,name=agentGUID" json:"agentGUID,omitempty"`
	AnalysisGUID *string `protobuf:"bytes,3,req,name=analysisGUID" json:"analysisGUID,omitempty"`
	// All of these fields are read from the Global Logger Boot Trace.
	// The ETW Process Start/End documentation provides more information. See http://msdn.microsoft.com/en-us/magazine/ee412263.aspx
	EventTimeStamp []int64 `protobuf:"varint,4,rep,name=eventTimeStamp" json:"eventTimeStamp,omitempty"`
	// Process Start = 0
	// Process End = 1
	EventType       []int32  `protobuf:"varint,5,rep,name=eventType" json:"eventType,omitempty"`
	ProcessId       []int32  `protobuf:"varint,6,rep,name=processId" json:"processId,omitempty"`
	ParentProcessId []int32  `protobuf:"varint,7,rep,name=parentProcessId" json:"parentProcessId,omitempty"`
	ImageFileName   []string `protobuf:"bytes,8,rep,name=imageFileName" json:"imageFileName,omitempty"`
	CommandLine     []string `protobuf:"bytes,9,rep,name=commandLine" json:"commandLine,omitempty"`
	// The fully qualified filename of the binary: i.e. '/Applications/Finder.app'. This field is derived from the command line.
	ImageFilepath []string `protobuf:"bytes,10,rep,name=imageFilepath" json:"imageFilepath,omitempty"`
	// MD5 for imageFileName
	ImageFileMD5     []string `protobuf:"bytes,11,rep,name=imageFileMD5" json:"imageFileMD5,omitempty"`
	SiteId           *string  `protobuf:"bytes,12,opt,name=siteId" json:"siteId,omitempty"`
	Uuid             *string  `protobuf:"bytes,13,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *OSXBootAnalysis) Reset()                    { *m = OSXBootAnalysis{} }
func (m *OSXBootAnalysis) String() string            { return proto1.CompactTextString(m) }
func (*OSXBootAnalysis) ProtoMessage()               {}
func (*OSXBootAnalysis) Descriptor() ([]byte, []int) { return fileDescriptor44, []int{0} }

func (m *OSXBootAnalysis) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *OSXBootAnalysis) GetAgentGUID() string {
	if m != nil && m.AgentGUID != nil {
		return *m.AgentGUID
	}
	return ""
}

func (m *OSXBootAnalysis) GetAnalysisGUID() string {
	if m != nil && m.AnalysisGUID != nil {
		return *m.AnalysisGUID
	}
	return ""
}

func (m *OSXBootAnalysis) GetEventTimeStamp() []int64 {
	if m != nil {
		return m.EventTimeStamp
	}
	return nil
}

func (m *OSXBootAnalysis) GetEventType() []int32 {
	if m != nil {
		return m.EventType
	}
	return nil
}

func (m *OSXBootAnalysis) GetProcessId() []int32 {
	if m != nil {
		return m.ProcessId
	}
	return nil
}

func (m *OSXBootAnalysis) GetParentProcessId() []int32 {
	if m != nil {
		return m.ParentProcessId
	}
	return nil
}

func (m *OSXBootAnalysis) GetImageFileName() []string {
	if m != nil {
		return m.ImageFileName
	}
	return nil
}

func (m *OSXBootAnalysis) GetCommandLine() []string {
	if m != nil {
		return m.CommandLine
	}
	return nil
}

func (m *OSXBootAnalysis) GetImageFilepath() []string {
	if m != nil {
		return m.ImageFilepath
	}
	return nil
}

func (m *OSXBootAnalysis) GetImageFileMD5() []string {
	if m != nil {
		return m.ImageFileMD5
	}
	return nil
}

func (m *OSXBootAnalysis) GetSiteId() string {
	if m != nil && m.SiteId != nil {
		return *m.SiteId
	}
	return ""
}

func (m *OSXBootAnalysis) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func init() {
	proto1.RegisterType((*OSXBootAnalysis)(nil), "OSXBootAnalysis")
}

var fileDescriptor44 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0xe9, 0xef, 0xd7, 0x39, 0xfd, 0xe3, 0x8b, 0xb6, 0x0e, 0x0a, 0x12, 0x0a, 0x82, 0xab,
	0xec, 0xdc, 0xb9, 0x31, 0x14, 0xa5, 0x60, 0xb5, 0xd0, 0x0a, 0x6e, 0x87, 0xe4, 0x58, 0x07, 0x32,
	0x99, 0x90, 0x99, 0x16, 0xea, 0xd2, 0x7b, 0xf2, 0x5a, 0xbc, 0x1d, 0x4f, 0x26, 0x12, 0x25, 0x2e,
	0xe7, 0x79, 0x9f, 0x99, 0xf7, 0x9c, 0x81, 0xc9, 0xe3, 0xfa, 0x39, 0xd4, 0xda, 0xde, 0xa4, 0x22,
	0x39, 0x18, 0x69, 0x82, 0x2c, 0xd7, 0x56, 0x9f, 0x7a, 0x2b, 0x6d, 0xec, 0x36, 0x47, 0xb3, 0x39,
	0x64, 0x58, 0xb2, 0xd9, 0x67, 0x13, 0xc6, 0x35, 0xdb, 0xf3, 0x81, 0x59, 0xa9, 0x70, 0x6d, 0x85,
	0xca, 0x78, 0xc3, 0x6f, 0x5e, 0xb6, 0xc2, 0xe1, 0xfb, 0x07, 0x77, 0xd0, 0x14, 0xd0, 0x3b, 0x03,
	0x26, 0xb6, 0x98, 0xda, 0xbb, 0xa7, 0xc5, 0x9c, 0x37, 0xc9, 0x60, 0x61, 0x8f, 0x8c, 0xf6, 0x6e,
	0x27, 0x63, 0xef, 0x1c, 0x06, 0xe2, 0xfb, 0x29, 0x97, 0xb7, 0x6a, 0xf9, 0x05, 0x8c, 0x70, 0x4f,
	0x97, 0x37, 0x55, 0x47, 0xdb, 0x6f, 0xfd, 0xed, 0xf8, 0x0f, 0xac, 0xd4, 0x68, 0x58, 0xde, 0x21,
	0xa3, 0x53, 0x20, 0x9a, 0x3a, 0x42, 0x63, 0x16, 0x31, 0xef, 0x3a, 0x74, 0x02, 0xe3, 0x4c, 0xe4,
	0xa4, 0xad, 0xaa, 0xe0, 0x9f, 0x0b, 0x26, 0x30, 0x94, 0x8a, 0x86, 0xbc, 0x95, 0x09, 0x3e, 0x08,
	0x85, 0xbc, 0x47, 0x98, 0x79, 0x47, 0xd0, 0x8f, 0xb4, 0x52, 0x22, 0x8d, 0xef, 0x65, 0x8a, 0x9c,
	0x39, 0xf8, 0xdb, 0xcd, 0x84, 0x7d, 0xe5, 0xe0, 0xf0, 0x31, 0x0c, 0x2a, 0xbc, 0x9c, 0x5f, 0xf1,
	0xbe, 0xa3, 0x23, 0xe8, 0x1a, 0x69, 0x91, 0x8a, 0x06, 0x7e, 0x83, 0xce, 0x53, 0x70, 0x6b, 0xf1,
	0x61, 0x71, 0xfa, 0x59, 0x33, 0xbc, 0x86, 0x19, 0x35, 0x05, 0x6f, 0xf2, 0xc5, 0x62, 0x1a, 0x18,
	0xcc, 0xf7, 0x98, 0x97, 0x9f, 0x1e, 0xe9, 0x24, 0xa0, 0x2d, 0x0d, 0x3d, 0x1d, 0x4e, 0x6b, 0x9f,
	0xbf, 0x2c, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0x41, 0xa5, 0xe5, 0xc3, 0x01, 0x00,
	0x00,
}
